apiVersion: v1
kind: Pod
metadata:
  name: curl
spec:
  containers:
  - name: curl
    resources:
      requests:
        cpu: '10m'
        memory: '32Mi'
      limits:
        cpu: '100m'
        memory: '256Mi'