# For the moment, just pushing a curl image for tests
apiVersion: v1
kind: Pod
metadata:
  name: curl
spec:
  containers:
  - image: odise/busybox-curl
    name: curl
    command:
      - "/bin/sh"
      - "-c"
    args:
      - "curl -sSL \
        --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
        -H \"Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)\" \
        https://kubernetes.default:443/api/v1/pods"
    # resources:
    #   requests:
    #     cpu: '10m'
    #     memory: '32Mi'
    #   limits:
    #     cpu: '10m'
    #     memory: '32Mi'
  serviceAccountName: watcher