apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcher
spec:
  template:
    spec:
      containers:
      - name: watcher
        resources:
          requests:
            cpu: '10m'
            memory: '32Mi'
          limits:
            cpu: '100m'
            memory: '256Mi'